### ISSUE TITLE
How to use Tensorflow 1.12.0 nowadays

### ISSUE THREAD

**Issue by oolegoon** [lxf8519/DL-hybrid-precoder#9]
I want to share the information with other people (beginners in ML and Python) that may face with problem how to run this code from scratch in 2024:
1) Install Python 3.6.0
2) pip install protobuf==3.19.6 (it works with Python 3.6.0)
3) pip install tensorflow==1.12.0 (I used this version for CPU, but you can install pip install tensorflow-gpu==1.12.0 and TF will work on GPU, but you need CUDA preinstalled, as I understand, because prebuilt libraries in TF use it)
4) pip install keras==2.2.4
5) pip install theano
6) Download datasets and copy in MIMO_dataset
7) Create folder Estimated_results in root directory
8) Run in root folder  python main_train_beamforming.py -train 1
9) Run in root folder  python main_train_beamforming.py -train 0
(it failed with  error "original_keras_version = f.attrs['keras_version'].decode('utf8')
                                 AttributeError: 'str' object has no attribute 'decode')"
 so I ran pip install 'h5py==2.10.0' --force-reinstall and the error is gone)
